apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ironcore-dev/ironcore/config/etcdless?ref=c6a8ace3ae7e07cf336816a2082bb273c6fad362
  - certificates.yaml

images:
  - name: apiserver
    newName: ghcr.io/ironcore-dev/ironcore-apiserver
    newTag: sha-c6a8ace
  - name: controller
    newName: ghcr.io/ironcore-dev/ironcore-controller-manager
    newTag: sha-c6a8ace

patches:
  - path: patch-apiserver-deployment.yaml
  - path: patch-apiserver-service.yaml
