apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/rook/rook/v1.18.4/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.18.4/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.18.4/deploy/examples/csi-operator.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.18.4/deploy/examples/operator.yaml

patches:
  - path: patch-operator.yaml
